### ISSUE TITLE
Support for ol.Object.Event

### ISSUE THREAD

**Issue by gkresic** [TDesjardins/gwt-ol3#114]
I'm trying to add support for `ol.Object.Event`, but I'm not sure which route to take:

If I add new `Event` subclass to `ol.Object` it will mask every current reference to `ol.events.Event` in subclasses (which is... almost every class in project :) ). This would be a clean solution, but it requires massive renaming across code base and is error prone.

If I name wrapper something like `ObjectEvent`, it looks kind of dirty and goes against OL's naming scheme.

Or I'm I just overthinking this?

My primary goal here is to add listeners for `change:center`, `change:resolution` and `change:rotation` to `ol.View`.

**Comment by ibaca** [comment]
`ol.Object.Event`and `ol.events.Event`are differents? why are there 2 of them?

**Comment by TDesjardins** [comment]
The event handling is a little bit confusing at first glance. Dealing with the mentioned change events are already possible but not as `Object.Event`. There is also already the dirty version with `ol.ObjectEvent` implemented. Tomorrow I will provide a clean solution. Happy if you could test it.
