### ISSUE TITLE
Should ol.format.Wkt#writeGeometry(ol.geom.Geometry) accept options?

### ISSUE THREAD

**Issue by gkresic** [TDesjardins/gwt-ol3#116]
OL's documentation says nothing about options:

https://openlayers.org/en/latest/apidoc/ol.format.WKT.html#writeGeometry

but source code uses it:

https://github.com/openlayers/openlayers/blob/master/src/ol/format/wkt.js#L406

**Comment by TDesjardins** [comment]
Maybe this is missing. I think you should open an issue at Openlayers project.

**Comment by gkresic** [comment]
OL maintainers confirmed it's a error in documentation and corrected it:

https://github.com/openlayers/openlayers/issues/7256#issuecomment-329698395

Since `writeGeometry` using options works already with current version of OL, I assume there are no blockers for addind that support into gwt-ol3. Before I prepare pull request, my only question is should I leave current version of `writeGeometry` without options (to avoid possible breakage if someone used that method, although it has been online for just a week or so)?

**Comment by TDesjardins** [comment]
@gkresic I guess writeGeometry options are optional. If this is the case you could simply overload the method.
