### ISSUE TITLE
Problems handling spatial filters to WFS.writeGetFeature

### ISSUE THREAD

**Issue by gmvtrmaga** [TDesjardins/gwt-ol3#117]
I will attach the images in order to have a graphical explanation. The summary is that, when addindg a spatial filter (polygon-array of coordinates like (longitude,latitude), the query is set as a polygon- array of coordinates like (latitude,longitude).

Is it a problem from gwt-ol3 or javascript openlayers library? 

Thanks in advance

Regards.

![screenshot_1](https://user-images.githubusercontent.com/25951539/30434658-1e4b7888-9968-11e7-8ce3-de603ace764d.png)
![screenshot_2](https://user-images.githubusercontent.com/25951539/30434659-1e4d8fc4-9968-11e7-995d-7c6bc997a704.png)
![screenshot_3](https://user-images.githubusercontent.com/25951539/30434657-1e483092-9968-11e7-9196-ba93d78a6968.png)

**Comment by TDesjardins** [comment]
@gmvtrmaga Could you clarify your problem? Maybe in a kind of current result vs. exprected result. I suppose you mean that the XML-output of the geometry isn't correct.

**Comment by gmvtrmaga** [comment]
@TDesjardins is that you have said.

Im expecting the query to have the same coordinates as the filter, but they are inverted. The result in the map is that, if I want to find water areas in canada I must set the area filter below Africa. Check the attached image: 
![screenshot_4](https://user-images.githubusercontent.com/25951539/30479087-f38eb2ca-9a13-11e7-90d4-b56baefc3071.png)

**Comment by TDesjardins** [comment]
At first sight it looks like a axis order problem. The axis order depends on the reference system. Have look at http://www.ogcnetwork.net/axisorder

Could you provide the code of the input geometry?

From my point of view the Javadoc o Coordinate isn't correct. Because 'x' isn't lon in any case.

**Comment by gmvtrmaga** [comment]
The geometry is generated by a Draw control: When I finish drawing, it sets the filter and send the request to the map server. 

Indeed, it is an axis problem, but I can't understand the reason.

![screenshot_1](https://user-images.githubusercontent.com/25951539/30534377-40775cb2-9c5e-11e7-8dc1-eb5589313ebd.png)

**Comment by TDesjardins** [comment]
@gmvtrmaga There is a method `createSpatialFilter(Geometry geometry)` in your code. Have you set the srsName parameter for the spatial filter? Could you share it?

**Comment by gmvtrmaga** [comment]
![screenshot_3](https://user-images.githubusercontent.com/25951539/30550567-1c5b8d3c-9c98-11e7-9203-a2bca297e198.png)

**Comment by TDesjardins** [comment]
Hm, looks ok 😄 . I think you have to figure out the point, when the coordinate order is changing. The last point is the creation of the spatial filter. Could you check if the coordinates in geometry have the order "lon lat" in method `createSpatialFilter(Geometry geometry)`?

**Comment by gmvtrmaga** [comment]
As I have shown in the third screenshot of the first post, the coordinates are inverted when creating a wfs Node from wfsWriteFeatureOptions. Spatial Filter is set with correct coordinates.

**Comment by TDesjardins** [comment]
Then you should create an issue at OpenLayers project.

**Comment by gmvtrmaga** [comment]
Ok, I will sen them this issue.

Thanks.
