### ISSUE TITLE
New functionality Draw features

### ISSUE THREAD

**Issue by ikzent** [TDesjardins/gwt-ol3#120]
Is there already a start of the draw implementation in OL3, if not where should one start ?
It seems that a draw function is available.

**Comment by TDesjardins** [comment]
Drawing is already available. You can use class [Draw](https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-client/src/main/java/ol/interaction/Draw.java) for this purpose.

**Comment by TDesjardins** [comment]
Please reopen this issue if you are missing something!
