### ISSUE TITLE
support for ol.source.Raster

### ISSUE THREAD

**Issue by d-eggert** [TDesjardins/gwt-ol3#128]
The openlayers api provides a raster class `ol.source.Raster` that enables you to execute per-pixel operations on a given source image via `ol.RasterOperation`.
Unfortunately I didn't find any correspondence in your gwt wrapper.
Are there any technical difficulties and do you plan to add support for this class in the future?

Regards,
Daniel

**Comment by TDesjardins** [comment]
Hello Daniel,

you are right, it isn't implemented yet. I see no technical difficulties to add this source. Do you want to provide a pull request?

**Comment by d-eggert** [comment]
Hi Tino,

i'm fairly new to this JsInterop stuff, but i will give it a try.
So, from a quick study of your wrapper classes, i derived the following todos:
- create class `ol.source.Raster` with `@JsType(isNative = true)`
- create class `ol.source.RasterOptions` with `@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")` providing setter Methods for the corresponding fields annotated with `@JsProperty`
- create interface `ol.RasterOperation` with `@FunctionalInterface` and `@JsFunction` defining a single function for the operation call

The `ol.RasterOperation` in openlayers is defined as `@typedef {function((Array.<Array.<number>>|Array.<ImageData>), Object): (Array.<number>|ImageData)}`. How do does this translate to Java? Simple generic parameters, like [GenericFunction.java](gwt-ol3/gwt-ol3-client/src/main/java/ol/GenericFunction.java) or [GeometryFunction.java](gwt-ol3/gwt-ol3-client/src/main/java/ol/GeometryFunction.java)?

If so, what will the actual parameters be? According to the openlayers documentation the ImageData is [https://developer.mozilla.org/en-US/docs/Web/API/ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData). Is that supported by your wrapper? In case of the raw pixel values, does the `Array.<Array.<number>>` translate to `int[][]` or `double[][]` or something else?

Regards,
Daniel
