### ISSUE TITLE
Satellite 

### ISSUE THREAD

**Issue by nseb** [TDesjardins/gwt-ol3#135]
Hi,
There is a possibility to display a satellite map like google maps?

Best Regards

**Comment by TDesjardins** [comment]
Hello @nseb ,

yes, of course! You could use Bing Maps source for example (https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-client/src/main/java/ol/source/BingMaps.java). OpenLayers supports a lot of sources. You only have to find a provider for your needs.

**Comment by TDesjardins** [comment]
Hello @nseb ,

I added an example for BingMaps. Have a look at the source code:

https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-demo/src/main/java/com/github/tdesjardins/ol3/demo/client/example/BingMapsExample.java

or just check the example on the demo page:

https://tdesjardins.github.io/gwt-ol3/#BingMapsExample

**Comment by masterdany88** [comment]
How about the commercial use of that satelite view?

**Comment by nseb** [comment]
I found this : 
https://www.microsoft.com/en-us/maps/licensing/options
