### ISSUE TITLE
Click events from Overlay

### ISSUE THREAD

**Issue by ezpzlmnsqz1337** [TDesjardins/gwt-ol3#136]
I created a simple popup (using ol.Overlay), that displays a box above the selected feature with additional information. There is also a button, to which I assign ClickHandler, but it never gets called. I tried setting `setStopEvent` to false on OverlayOptions, but that just makes the map receive some event, but it never gets to my click handler.

I can see that my SelectFeature is receiving this click (even though it is a click on a button in an overlay, so no select at all), but the handler I add to the button by `btn.addClickHandler(event -> doSomeStuff())` is not called.

I can see that other people have this issue, so it is not probably an issue with this wrapper, but with OL in general, but just how to register my button so that it will react to click?

**Comment by ezpzlmnsqz1337** [comment]
I tried your example with and without "setStopEvent" set on my overlay. If false, nothing gets called. With it set to true, SelectFeature gets this click, but again not this EventListener. Can't it be because when I set an Element to an overlay, it gets all its browser events removed?

**Comment by TDesjardins** [comment]
@ezpzlmnsqz1337 `setStopEvent` isn't relevant for this listener. I added a temporary branch `overlay_click` with an modified working example. See commit https://github.com/TDesjardins/gwt-ol3/commit/49e6fff9b427ad3695bc9cc919237ab9a4509980 .
 
Could you check if it works for you?

**Comment by ezpzlmnsqz1337** [comment]
Thanks you! It was the `Event.sinkEvents` that I was missing :) Sorry, not experienced with it, never used it before. From the name of the method I would expect that it 'sinks' them, like "put them down" or "remove" :D Now it works fine, just this one line of code was missing. Thanks.

**Comment by TDesjardins** [comment]
So I think this can be closed. Please reopen if necessary. I will remove the temporary branch.
