### ISSUE TITLE
Style function should have two parameters

### ISSUE THREAD

**Issue by Fractaliste** [TDesjardins/gwt-ol3#137]
According to the documentation the style function is a:

`function that takes an module:ol/Feature~Feature and a {number} representing the view's resolution. The function should return a module:ol/style/Style~Style or an array of them. This way e.g. a vector layer can be styled.
`

In following code the resolution number is missing:

 https://github.com/TDesjardins/gwt-ol3/blob/b30f6cf45ed7050142e0543eda96b9b1997ba20a/gwt-ol3-client/src/main/java/ol/layer/VectorLayerOptions.java#L72

Do you eventually consider to have a GenericBiArgs functionnal interface like https://github.com/Fractaliste/gwt-ol3/blob/master/gwt-ol3-client/src/main/java/ol/gwt/GenericBiArgFunction

**Comment by TDesjardins** [comment]
@Fractaliste GenericBiArgFunction would be a solution but I would prefer a special type `ol.style.StyleFunction` in favour of readability.
There is also an open [issue](https://github.com/TDesjardins/gwt-ol3/issues/90) with the second parameter which maybe still appears. I will have look.

**Comment by TDesjardins** [comment]
@Fractaliste Should work now. Please reopen if it doesn't work for you.
