### ISSUE TITLE
Consider uploading artifacts to a central maven repository

### ISSUE THREAD

**Issue by TDesjardins** [TDesjardins/gwt-ol3#26]
Uploading gwt-ol3 artifacts to a central maven repository would be facilitate the use of it in maven projects. Probably this process can be supported by CI.

Ressources:

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by ibaca** [comment]
If you have interest, I can help with this. If you want to use sonatype and deploy using the packages starting with `de.desjardins` you can request access sending a message like this https://issues.sonatype.org/browse/OSSRH-21191 and be able to demostrate that you have access to this domain `de.desjardins`. So if they grant access to `de.desjardins`, you will be able to deploy `de.desjardins.ol3:gwt-ol3`. http://central.sonatype.org/pages/ossrh-guide.html

If you go ahead, I'll create a pull request with the changes required in your pom. And you will need to configure gpg and upload your public key to a server (http://central.sonatype.org/pages/working-with-pgp-signatures.html).

Recommendation: The client lib is in the package `ol`, I don't like it 😜, I prefer `de.desjardins.ol3` which is the maven group of your project, but if you are sure about this, at least you should move `GwtOL3.gwt.xml` into `ol` package.

**Comment by TDesjardins** [comment]
Hello @ibaca ,

yes, I have interest. Thanks for your offer. I already created an account at central sonatype. What do you mean with demonstrate access to the domain `de.desjardins`? The domain doesn't really exist. It's only a namespace.

I also don't like the package `ol` but this is the original namespace of ol3. When I created the wrapper, the idea was to make it as closely as possible to the ol3 API. The advantage is that you can better find your way when developing the wrapper and you can use the apidoc of ol3. You also don't need to add jsinterop namespace annotations.
When thinking in Maven it will be usefull to change the namespace. Then all the stuff could be deployed under the same namespace, right?

Regards

Tino

**Comment by ibaca** [comment]
Yep, maybe you are right, ol is not that bad, even is more natural. This is a JS wrapper, and be close to the JS lib might be a good idea. But, what about moving the GwtOL3.gwt.xml into ol package?

About 'demonstrate access'; just request access to de.desjardins, someone from sonatype will ask you something, or maybe they just grant access, not sure 😛 just ask.

**Comment by TDesjardins** [comment]
What are the benefits when moving `GwtOL3.gwt.xml` into `ol` package? There are a lot of files directly under `ol` that are then not in the source path.

**Comment by ibaca** [comment]
You can add this `<source path=""/>` to the GwtOL3.gwt.xml so the module can be inside its own package. IMHO is more common (used in libs like https://github.com/intendia-oss/rxjava-gwt/blob/master/src/main/resources/rx/Rx.gwt.xml). I suppose there aren't any specific benefits.

**Comment by TDesjardins** [comment]
It is more common because rxjava-gwt is a reference project ?! ;-)
The module xml files are moved now.
Also the groupid `com.github.tdesjardins` is accepted at sonatype. So I will change it in the maven configuration. `de.desjardins` was not accepted because of the missing ownership of the domain.

**Comment by TDesjardins** [comment]
The sonatype configuration is prepared: https://issues.sonatype.org/browse/OSSRH-24393 .
I also changed the groupid in the maven configuration and uploaded a public gpg key to a server. Now I have to configure the maven deploy plugin, right?

**Comment by ibaca** [comment]
This pull request https://github.com/TDesjardins/gwt-ol3/pull/33 should cotain all configuration you need. You can do right now a `mvn clean release:prepare release:perform`, this will create various commits, one tag and will deploy to the sonatype staging repository. Don't worry if something goes wrong, you can always remove the tag, make a hard reset and push force to this repo and discard the staging repo created in oss.sonatype.org.

**Comment by TDesjardins** [comment]
Thanks @ibaca ! I tried different parameters and configurations (settings.xml) with `release:perform` and now the checkout seems to work but I get the following error message when executing goal `deploy site-deploy`:
`Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.1:sign (sign-artifacts) on project gwt-ol3: Cannot obtain passphrase in batch mode -> [Help 1]`
I suppose that I have to set some settings in settings.xml for gpg signing. I already set a passphrase but   that doesn't fix the issue. Maybe I need references to the public and the private key. How the process knows where to get the gpg infos?

**Comment by ibaca** [comment]
First of all, I see that you are using a stable version right now, **you should change it to a SNAPSHOT version** (you can use `mvn versions:set -DnewVersion=2.5.0-SNAPSHOT`), the release plugin will ask you which stable version do you want to use in the first step.

About your problem, try to execute one goal a time, I think that the problem is related to `deploy`, that cannot be executed in batch mode because it need the password to use gpg. In any case, do not use --batch-mode to fix this error.

And maybe you are having some problems with the site-deploy, we can see whats happening later, but for now I thinks its better that you just **remove the distibutionManagement.site section**. I think that deploying the showcase to this url will be much more useful.

**Comment by TDesjardins** [comment]
That's a good hint. I havn't used the batch mode intentionally. I use the maven integration of eclipse which runs all commands in batch mode :-) .
With the console I managed it somehow and now there are artifacts at central maven repository. I don't know if this is a correct release because all artifacts are in a folder snapshot, also in the release repositories:

https://oss.sonatype.org/content/groups/public/com/github/tdesjardins/
https://oss.sonatype.org/content/groups/staging/com/github/tdesjardins/
https://oss.sonatype.org/content/repositories/snapshots/com/github/tdesjardins/

Could you check this?

Furthermore I think also the module gwt-ol3 should be exluded from the release.

**Comment by ibaca** [comment]
It's not published in central, don't worry. You should make the `close` and `release` in oss.sonatype.org, but do not make it until you confirm everything is ok 😛.
<img width="747" alt="screen shot 2016-08-27 at 09 03 07" src="https://cloud.githubusercontent.com/assets/1042225/18025808/48eba7cc-6c35-11e6-9320-445e55c50db8.png">

User always the terminal, and do not keep open eclipse during release (at least for now, eclipse can auto-compile, adding files to the final artifact or making it fail to build, etc).

Releasing should be just `mvn clean` (this is a good idea), `mvn release:prepare` (you should set a stable version, and configure the next snapshot version), `mvn release:perform` (should deploy to sonatype creating the staging repository in oss.sonatype.org which should be closed and released).

**Comment by ibaca** [comment]
Current version of the master branch is still a stable version, please change to 2.5.0-SNAPSHOT.

**Comment by TDesjardins** [comment]
gwt-ol3 is now available at central maven repository. Thank you very much @ibaca !
