### ISSUE TITLE
Integrating OL3 into tabpanel of GWT Application 

### ISSUE THREAD

**Issue by misiakj** [TDesjardins/gwt-ol3#42]
I would like to say thank you for creating the OL3 GWT wrapper, it looks like it's going to be very useful for integrating map functionality into a GWT application. I see that in your demo you add a 
<div id="map" class="map"></div> line to your .html file and then assign the map to that element. I also see that we can add a map to a GWT app by placing it in a panel that is placed directly on the RootLayoutPanel.

Currently I am trying to place the map in a panel (with id "map") that exists in a TabLayoutPanel several layers down from the RootLayoutPanel, but the map doesn't seem to find that object, I was wondering if there was a current standard way of placing the OL3 map in a panel that is not attached to the RootLayoutPanel but is instead several children down?

Thank You,

Jon

**Comment by TDesjardins** [comment]
Hello Jon,

you are welcome. Could you provide a code snippet that shows your problem? If you have a div with id "map" in the DOM the map should be displayed, in my opinion this is independant from the DOM hierarchy level.

Regards

Tino

**Comment by misiakj** [comment]
I actually found a solution but thank you for the quick response. I was setting up the map information in the constructor of a widget that was several layers deep in the widget that was actually being added to the RootLayoutPanel so it appears that the map information would look for the Div element, but since the greater object being added to the RootLayoutPanel hadn't finished creation yet it was not yet on the DOM and our Div couldn't be found.


Example below for anyone who has a similar issue.

 @Override
	public void onModuleLoad() {
		RootLayoutPanel.get().add(new FastLayout()); // add our layout to our root panel
	}


FastLayout ->Creates several SubWidgets-> One of those Widgets Creates the Map Div in it's UI Binder.

The solution was to create the map information in module load after the line creating the FastLayout.
