### ISSUE TITLE
Image as marker icon

### ISSUE THREAD

**Issue by mazlixek** [TDesjardins/gwt-ol3#55]
Is it possible to set image as marker icon? I was using it in old GWT OL and I was also able to change that icon on the fly (for example I have road signal icon and when the road signal red lamp is activated, I change the icon appropriately).

Or is it possible to use SVG icon?

I found that I can set style to feature, and with creating this style I can pass Image as parameter, but I don't know how to instantiate the Image.

**Comment by mazlixek** [comment]
Thanks for the answer. I thought that it is probably not implemented, as the Image or Icon interfaces are empty (no methods), but I was not sure.

I guess it is just the matter of adding those methods in ol.style.Image, but I guess I also need to provide a way how to create the Icon/Image, which I'm not really sure how. I can try though.

**Comment by TDesjardins** [comment]
@mazlixek 
I added some properties and created an example for markers: https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-demo/src/main/java/com/github/tdesjardins/ol3/demo/client/example/MarkerExample.java

Could you check this?

**Comment by mazlixek** [comment]
I just tried it and it works! Thanks a lot! I tried to add it myself but I wasn't sucessful. I didn't know that I should use Point for this.

**Comment by TDesjardins** [comment]
You are welcome.
