### ISSUE TITLE
gwt-ol3 for GWT 2.7 on Maven?

### ISSUE THREAD

**Issue by francescomangiacrapa** [TDesjardins/gwt-ol3#56]
Hi TDesjardins,

can you deploy on Maven Central also the last version of gwt-ol3 for GWT 2.7? if possible?
Unfortunately, at the moment, I can't use the latest version (for GWT 2.8) because in the environment where I deploying my web-app several components are developed/compiled using GWT 2.7, and this last is shared by all.

Thanks.
Regards,
Francesco

**Comment by TDesjardins** [comment]
Hello @francescomangiacrapa , 

what about using Jitpack for now?


The latest Tag for GWT 2.7 branch is `v1.3.0` :

https://jitpack.io/#TDesjardins/gwt-ol3/v1.3.0



Regards

Tino

**Comment by francescomangiacrapa** [comment]
Hi @TDesjardins,

thanks for your reply.
I will test Jitpack solution asap in order to use gwt-ol3 v1.3.0
I think it is a great idea.

Regards,
Francesco

**Comment by TDesjardins** [comment]
O.k. you can reopen this issue if you have problems with that.
