### ISSUE TITLE
How to add pointerMove to a SelectFeature?

### ISSUE THREAD

**Issue by brauchle** [TDesjardins/gwt-ol3#66]
Hi,

I'm trying to implement the possiblity to select a polygon by mouse-over.
Example for JS: [http://www.freytag.org.uk/ol/hover.html](http://www.freytag.org.uk/ol/hover.html):
```
var highlighter = new ol.interaction.Select({
        condition: ol.events.condition.pointerMove
});
map.addInteraction(highlighter);
```

I only got it to work with a select-by-click-Feature (as in your Demo), but i don't get it to work with the pointerMove-Event - i just don't know how to set the condition and unfortunately there are no examples for this in the demo.

Would be great if you can give me any advise on how to solve this!

Andreas

**Comment by TDesjardins** [comment]
Hello Andreas,

I just added some standard conditions to the repository. You can now use this property:

https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-client/src/main/java/ol/events/condition/Condition.java#L38

and set it here:

https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-demo/src/main/java/com/github/tdesjardins/ol3/demo/client/example/SelectFeaturesExample.java#L117
```
SelectOptions selectOptions = new SelectOptions();
selectOptions.setCondition(Condition.getClick());
   
// create a select interaction
final Select selectFeature = new Select(selectOptions);
map.addInteraction(selectFeature);
```

**Comment by brauchle** [comment]
works like a charm - thanks a lot for the quick response!
