### ISSUE TITLE
Consider using https for openlayers; demo is broken

### ISSUE THREAD

**Issue by tbroyer** [TDesjardins/gwt-ol3#68]
The demo is broken when loaded from https://tdesjardins.github.io/gwt-ol3/ because openlayers is loaded over HTTP; but openlayers.org supports HTTPS too. So you should use `https://openlayers.org` or a scheme-relative `//openlayers.org`.

BTW, I have the HTTPS Everywhere extension in my browsers that automatically loads sites over HTTPS when known to work (as is the case for *.github.io sites)

**Comment by ibaca** [comment]
Thanks!
