### ISSUE TITLE
OLFactory.createColor not working with String

### ISSUE THREAD

**Issue by enpi** [TDesjardins/gwt-ol3#73]
I have been testing some of the functionality and creating a color using a String is not possible. It works fine using an array.

https://openlayers.org/en/latest/apidoc/ol.html#.Color

And looking through the API it is only defined as an array.

By the way, I really appreciate your work! Thx :)

**Comment by TDesjardins** [comment]
Thanks @enpi !

I suppose you are using this method: 
https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-client/src/main/java/ol/OLFactory.java#L238

...which is not working for you?

**Comment by hmgrenner** [comment]
Yeah, this method ( sry for not pointing it out ). Thx for fixing it!

**Comment by TDesjardins** [comment]
Fixed with commits:
https://github.com/TDesjardins/gwt-ol3/commit/042021a2cd961a5f781a81ae97bc14b1ba8e8705
https://github.com/TDesjardins/gwt-ol3/commit/f2dd7e7469af62565f9d41e4525d4675ede9da58

You can close this issue if it works for you.
