### ISSUE TITLE
Set ProxyHost

### ISSUE THREAD

**Issue by enpi** [TDesjardins/gwt-ol3#74]
Is there a possibilty to set the proxy host like in Openlayers 2 ?

https://github.com/geosdi/GWT-OpenLayers/blob/master/gwt-openlayers-client/src/main/java/org/gwtopenmaps/openlayers/client/OpenLayers.java#L53

**Comment by TDesjardins** [comment]
It would be a nice feature but nope, there isn't any feature imlemented, yet. See:

https://github.com/openlayers/openlayers/issues/3367
http://gis.stackexchange.com/questions/171568/create-and-show-a-vector-layer-from-geoserver-using-openlayers3

At this time you have to modify all your URLs yourself.
