### ISSUE TITLE
How to export the map to an image file?

### ISSUE THREAD

**Issue by gmvtrmaga** [TDesjardins/gwt-ol3#75]
Hi,

I'm having problems to implement the export tool ( example here: https://openlayers.org/en/latest/examples/export-map.html ). I think the absence of render.event is the main problem here. Maybe I am missing a better way to solve this, I readed the code but I couldn't find anything.

Would be great if you can help me with this.

Mario.

**Comment by TDesjardins** [comment]
Hello @gmvtrmaga ,

I added the `ol.render.Event` to gwt-ol3. There is a property `getContext()` which you can use. The type is tentatively `JavaScriptObject`. For the last steps you can use JSNI. Later we could probably use elemental.
Please note that the export demo uses a FileSaver script.

**Comment by gmvtrmaga** [comment]
Thank you very much!

It works perfectly, I just added the library and used your new contribution.

Regards.
