### ISSUE TITLE
Vector open street map as a source

### ISSUE THREAD

**Issue by mazlixek** [TDesjardins/gwt-ol3#76]
Hello,

I recently wanted to switch to vector map representation. I found out that I can download XML file from OSM. And here http://gis.stackexchange.com/questions/169387/using-local-openstreetmap-osm-map-with-openlayers-3 I found that I can use directly that file as a source for the map in OL3.

But it is not implemented here I think. I used GeoJSON for now, but are there any plans to add OSMXML direct support?

I guess it is just this http://openlayers.org/en/latest/apidoc/ol.format.OSMXML.html class, so I can try it myslef. I just want to know if I am not missing something that is already implemented.

Thanks

**Comment by TDesjardins** [comment]
It's not implemented yet. You are welcome to fill this gap. It's just this one class you mentioned, not much effort.

**Comment by TDesjardins** [comment]
I close this issue. You can reopen it if it is not working for you.
