### ISSUE TITLE
ol.StyleFunction support

### ISSUE THREAD

**Issue by mazlixek** [TDesjardins/gwt-ol3#80]
Since now it is possible to add OMS vector map as a source, it would be nice if there will be support for styles that varies with zoom level. For example displaying street names from a certain zoom level etc. As far as I know there is no support for http://openlayers.org/en/master/apidoc/ol.html#.StyleFunction now.
Are you planning on adding this feature? Or should I try it myself? I'm not that much sure on how to implement it so any advice would be nice.
I only saw an example here: https://openlayers.org/en/latest/examples/vector-osm.html?mode=raw

**Comment by TDesjardins** [comment]
You can use this method: https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-client/src/main/java/ol/layer/Vector.java#L62

**Comment by mazlixek** [comment]
Well I can't figure out how to use it. Let's say I want to hide buildings if mapZoom level is less than 15.
Let's say that I can determine that feature is building by:
`if(feature.get("building")=="yes"){//it is building}`

I have this:
```
mapLayer.setStyle(new GenericFunction<Feature, Style[]>() {

      @Override
      public Style[] call(Feature object) {
          //  what to do here? 
      }
    });
```

Sorry to bother you, I just cannot figure it out.

**Comment by mazlixek** [comment]
OK I have no idea how, but it works. Here is my sample code:
```
mapLayer.setStyle(new GenericFunction<Feature, Style[]>() {

      @Override
      public Style[] call(Feature feature) {
        List<Style> style = new ArrayList<>();
        String text = feature.get("name");
        if (feature.get("building") == "yes") {
          logger.log("building " + feature.get("building"));
          style.add(MapStyles.getStyle(MapStyles.BUILDING, text));
        }
        if (feature.get("landuse") != null) {
          logger.log("landuse " + feature.get("landuse"));
          style.add(MapStyles.getStyle(MapStyles.COMMERCIAL, text));
        }
        if (feature.get("natural") != null) {
          logger.log("natural " + feature.get("natural"));
          style.add(MapStyles.getStyle(MapStyles.FOREST, text));
        }
        if (feature.get("natural") == "water" || feature.get("waterway") != null) {
          logger.log("water " + feature.get("waterway"));
          style.add(MapStyles.getStyle(MapStyles.WATER, text));
        }
        if (feature.get("highway") != null) {
          logger.log("highway " + feature.get("highway"));
          style.add(MapStyles.getStyle(MapStyles.HIGHWAY, text));
        }
        if (feature.get("highway") == "bus_stop") {
          logger.log("bus_stop " + feature.get("bus_stop"));
          style.add(MapStyles.getStyle(MapStyles.BUS_STOP, text));
        }
        if (feature.get("railway") != null) {
          logger.log("railway " + feature.get("railway"));
          style.add(MapStyles.getStyle(MapStyles.RAILWAY, text));
        }
        if (feature.get("leisure") != null) {
          logger.log("leisure " + feature.get("leisure"));
          style.add(MapStyles.getStyle(MapStyles.PARK, text));
        }
        if (feature.get("leisure") == "park") {
          logger.log("park " + feature.get("park"));
          style.add(MapStyles.getStyle(MapStyles.PARK, text));
        }
        style.add(MapStyles.getStyle(null, null));
        return style.toArray(new Style[0]);
      }
    });
```

I mean... how does it know which style to add to which feature? Could you explain?
But it works and on each map movement it is reevaluated, so I guess I can check zoom level in this function and send it as parameter to my MapStyles.getStyle() function to hide buildings at low zoom levels etc.

Thanks

**Comment by TDesjardins** [comment]
It's just magic ;-) 
With StyleFunction you have more control over styling each feature. The input argument is the feature to style. It is only needed to have information to create styles for this feature. The return value is the style you want to give this feature. OpenLayers will then automatically put this style information to this feature.

**Comment by mazlixek** [comment]
Oh I guess I understand it now, I return only Style[] array which has just one style object in it. I thought There are all the styles in the array and that was why I didn't understand how the hell OL know what style goes where.

Thanks man, It works like charm now when I added different styles for different zoom levels! I can even change the size of the point elements on map, so they are easier to click when fully zoomed.

**Comment by TDesjardins** [comment]
I have also added StyleFunction-property to VectorLayerOptions. Could you check if this is also working for you? You could then close this issue.

**Comment by TDesjardins** [comment]
... and yes a feature can have more than one style. Because of this the return type is a style array ;-)

**Comment by mazlixek** [comment]
I just tried it and it works too so you can close this issue.

Just maybe one more small question:
If I return more than one style in the array in the function, lets say 3, what would happen to the feature? Will all be applied at the same time? Or is there some rule like 1st style in the array is for not selected feature, 2nd for selected feature... etc.?

**Comment by TDesjardins** [comment]
Don't know it for ol3. In ol2 there are render intents and filters for feature and state depending styles.
