### ISSUE TITLE
WFS and GetFeature format

### ISSUE THREAD

**Issue by Rezumadora** [TDesjardins/gwt-ol3#81]
Hello,

i am trying to read features using WFS, but i don't get which is the corresponding "Node" class in Java. 

Could you implement a request example with the GetFeature format?

Thx :)

**Comment by TDesjardins** [comment]
@Rezumadora The WFS format wasn't implemented, yet. I added some base functionalities as a starting point:
https://github.com/TDesjardins/gwt-ol3/commit/2cc97bf4f008c8c01ae281c4a53a741e25f2e8ed
You are welcome to extent it.

**Comment by ssagredo** [comment]
Thank you for the new functionalities!

**Comment by Rezumadora** [comment]
Thank you for the new functionalities!

**Comment by TDesjardins** [comment]
GetFeature format works now including filters. There is also a new [WFS example](https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-demo/src/main/java/com/github/tdesjardins/ol3/demo/client/example/WfsExample.java) that shows the use.
