### ISSUE TITLE
Background images for icons

### ISSUE THREAD

**Issue by OscarSotodosos** [TDesjardins/gwt-ol3#82]
Hi, 

In Ol2 you could use a background image and use an icon image. Now it is only possible to choose an icon image. Is there a possibilty to still use both? I need to draw a background image like a circle and put an icon in this circle. 

And create the different images (like a circle with the icon inside) is not viable, because i have over 500 different combinations that would need to be created dynamically. 

Thanks for your time.
Regards

**Comment by TDesjardins** [comment]
Hello @OscarSotodosos ,

I think this is a general OpenLayers question you could raise in the OpenLayers community. If this is possible in OpenLayers, it is also feasable in gwt-ol3. If there is a solution I can help you to do it with gwt-ol3.

Regards

Tino

**Comment by TDesjardins** [comment]
@OscarSotodosos What's the status? Have you asked the Openlayers community for that feature?

**Comment by TDesjardins** [comment]
As already said this is not a gwt-ol3 specific issue. If this is feasable with OL3 we can also implement this in gwt-ol3. You could reopen this issue if there is a solution for OL3.

**Comment by TDesjardins** [comment]
Hello @OscarSotodosos ,

have you already found a solution? If not have a look at this approach: https://github.com/openlayers/openlayers/issues/6597
