### ISSUE TITLE
Bing Maps support?

### ISSUE THREAD

**Issue by gkresic** [TDesjardins/gwt-ol3#89]
Is there a reason gwt-ol3 does not provide wrappers for Bing maps (supported in OL)?

https://openlayers.org/en/latest/apidoc/ol.source.BingMaps.html

I've created a patch, basicaly just two additional simple JsInterop wrappers:

`ol.source.BingMaps extends ol.source.TileImage`
and
`ol.source.BingMapsOptions extends ol.source.TileImageOptions`

It works and if there are no issues that I'm not aware of (license?) I can provide a pull request.

**Comment by TDesjardins** [comment]
Hello Gordan,

nope there is no special reason. It is only not implemented yet. Pull requests are welcome. Please also provide a test and an example. You can copy the license header from one of the other files.

Regards

Tino
