### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cukurvate** [TDesjardins/gwt-ol3#92]
Hi,
first of all, thank you for developing GWT-OL3.

I would like to ask, are you planning on releasing a new version? I see that some essential features (particularly, clustering) are added after the 3.0.0 version release, which would be great to try out.

Also, is it currently possible to create a popup?

**Comment by TDesjardins** [comment]
I want to release v4.0.0 soon. There are some issues left I want to include.

Popups already possible. You can use ol.Overlay in combination with map click or selection events. See http://openlayers.org/en/latest/examples/popup.html

**Comment by TDesjardins** [comment]
The new release v4.0.0  is now available and already in Maven central.
