### ISSUE TITLE
Include ol.format.filter to WFSWriteFeatureOptions?

### ISSUE THREAD

**Issue by gmvtrmaga** [TDesjardins/gwt-ol3#94]
Hi,

I have just realized that WFS filters are not included in the WFS class, so we are not able to include these to the request. I tried to add them in WFSFeatureOptions but I could not make the query work. I wonder if there is something that I am missing.

Regards, and thanks in advance.

**Comment by TDesjardins** [comment]
Hello @gmvtrmaga ,

could you share the code?

**Comment by gmvtrmaga** [comment]
I have implemented the following package
[filter.zip](https://github.com/TDesjardins/gwt-ol3/files/1156141/filter.zip)

and added this code to WFSWriteFeatureOptions class:
 /**
     * 
     * @param filter
     */
    @JsProperty
    public native void setFilter(Filter filter); 


It is probably wrong, as I have been trying different ways to add it.

**Comment by TDesjardins** [comment]
GetFeature format works now including filters. There is also a new [WFS example](https://github.com/TDesjardins/gwt-ol3/blob/master/gwt-ol3-demo/src/main/java/com/github/tdesjardins/ol3/demo/client/example/WfsExample.java) that shows the use. I only tested the IsLike filter. You can reopen this issue if other filters will not work.

**Comment by gmvtrmaga** [comment]
First of all, thank you for this enancement, it is being useful in many ways. I have been making custom examples to test all the filters and they work fine overall.

However, I have just discovered that setUpperBoundary and setLowerBoundary functions (ol.format.filter.isBetween class) are not working. I catch this exception in debug mode: 

       TypeError: ((intermediate value)(intermediate value) , ib_0_g$).setLowerBoundary is not a function

The same in setUpperBoundary

It is not a major problem as I can set the boundaries by replacing the filter, because the constructor works fine.

Should this setters be deleted? Maybe the same problem will occur in setGeometry function (ol.format.filter.spatial), I am going to test it soon.

Regards

**Comment by TDesjardins** [comment]
@gmvtrmaga Yes, the same will happen with setGeometry function because there are no functions but properties. I will fix this soon.

**Comment by TDesjardins** [comment]
Should work now with this fix: https://github.com/TDesjardins/gwt-ol3/commit/7d7712b5c84f54ed91464419802a8d8287821a86
