### ISSUE TITLE
Customizable Map.forEachFeatureAtPixel

### ISSUE THREAD

**Issue by gkresic** [TDesjardins/gwt-ol3#96]
`Map.forEachFeatureAtPixel` should have additional prototype with `FeatureAtPixelOptions` for customizations.

Will provide a patch soon.

Unrelated to this issue, I would like to ask @TDesjardins if this workflow "file an issue" -> "provide a patch" is valid? I looks like there are considerable amount of missing features in gwt-ol3 (which is completely understandable) so I'll have to spam this project a bit. I could pack several improvements in one pull request, but then I risk that because of one misimplemented feature whole pull request gets rejected. Note that I don't mind filing an issue for each feature implemented, I'm just asking if that is OK with maintainer.

**Comment by TDesjardins** [comment]
@gkresic Please provide pull requests by feature! If you pack several improvements in one pull request the review is not possible. It's not neccessary to open an issue, but this maybe saves you from wasting your time (e.g double implementation or an existing feature). It isn't spam it's communication ;-)
